### ISSUE TITLE
How about rewriting this to allow dependency injection?

### ISSUE THREAD

**Issue by jtlapp** [seeden/kysely-orm#1]
I love what you've done here, but I find myself not wanting to use it because it doesn't allow dependency injection. Quite a bit of flexibility is lost by hardcoding repository behavior as static methods. For example, the code gets convoluted if we want a function that acts on any model conforming to a particular interface. Suppose I want to generically act on any of several similar tables? Or suppose I want to generically act on either of two databases? Or suppose I want to stub a table for testing purposes?

I've written several servers that rely on statics to access the underlying database, as you've done here, but I'm now finding that this is not how large scale applications are written. I recently decided to abandon this approach and do things the modern way.

Do you have any interest in rewriting this to put repository behavior on instance methods? I'd be glad to help or even do it all. This would require revising the approach to mixins.

**Comment by seeden** [comment]
Then you can use kysely directly for this purpose.
