### ISSUE TITLE
No type info on model query find* response

### ISSUE THREAD

**Issue by vasyas** [seeden/kysely-orm#2]
Hi!

I've followed the steps in README.md but got an issue with the type of model query response.

Having the table types:
```
interface Users {
  id: Generated<number>;
  name: string;
  email: string;
}

interface DB {
  users: Users;
};
```

and the model defined:
```
export default class User extends db.model('users', 'id') {
  static findByEmail(email: string) {
    return this.findOne('email', email);
  }
}
```

My query doesn't have return type info, which is breaking type-safety in queries:
```
import User from "./User"

async function demo() {
  const user = await User.findByEmail("aa")
  console.log(user.aaa) // should fail here, b/c User doesn't have `aaa` field?
}
```

[Sandbox with repo](https://codesandbox.io/p/sandbox/typescript-node-forked-p2v228?selection=%5B%7B%22endColumn%22%3A1%2C%22endLineNumber%22%3A7%2C%22startColumn%22%3A1%2C%22startLineNumber%22%3A7%7D%5D&file=%2Fdemo.ts)

Is this expected to be working?

**Comment by vasyas** [comment]
More info for it.
1. It is reproducible only for find* methods
2. It is reproducable only latest kysely release, 0.23.5.

**Comment by seeden** [comment]
I will check it with last version but I am working on something else these days.

**Comment by seeden** [comment]
Fixed in latest version
